### PR TITLE
[CIRCLE-17179] Prototype of an Image Tag browser

### PR DESCRIPTION
**Pull request by glenjamin**
### Checklist
- [ ] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [ ] I've updated the documentation if necessary.

### Motivation and Context

The idea here is to produce a little standalone site that can be used to navigate the big list of tags more effectively.

### Description

I decided to use React and create-react-app, as they made the app itself pretty neat. I've done a redux-like pattern, but didn't bother messing around with getting actual redux wired up for a small app like this.

We should be able to set CI up to publish the built assets to the gh-pages branch by adding a read-write deploy key.

I wasn't able to make this work using https://circleci.com/docs/2.0/docker-image-tags.json because it doesn't allow CORS requests. As it's only a cache of the real data from docker hub, I took the approach of duplicating that logic into this build step.

I set the CI job up to store the artifacts, so we can see a preview
https://21807-85091879-gh.circle-artifacts.com/0/home/circleci/project/shared/browser/build/index.html

With this approach we'd need to add the rebuild of this site into the end of the overnight publish workflow.

### CODE REVIEW

**Comment by iynere** [comment]
@glenjamin this looks great to me! obviously it's very much a prototype, but we're going from nothing to something, & the core functionality is here, imo.

some things that would be nice-to-have:

- use some CircleCI UI (the orb registry / circleci site are also built in react—can we drop in some UI components here?)
- would be nice if tags were links to specific Dockerfiles for those tags

our team is not prioritizing new feature work on this repo, as we're working on our new images prototype, so this is an awesome freebie to have, i think. my preference would be to merge this, tell customers about it, & gather feedback to drive our decision-making as we flesh out our new images documentation:

https://github.com/circleci-public/cimg-docs

@felicianotech what do you think ?

**Comment by glenjamin** [comment]
@iynere @felicianotech did you want to merge this? I'll probably have some time to tidy it up shortly

**Comment by iynere** [comment]
@glenjamin i'm really not sure, we can talk about it again in our standup

**Comment by iynere** [comment]
@glenjamin we're into merging it! we're going to send you a list of features/functionality that we'd want to see working here before we're comfortable publishing it.

also, i've linked this PR to a Jira ticket for basically this work that, which came out of an old images incident late last year but my team was never able to find the time to complete, since we're focusing on new images.

thank you !!

**Comment by iynere** [comment]
@glenjamin so, here's what we feel should DEFINITELY be present in this PR before we merge—happy to work with you to get it the rest of the way, also !
> - tags should link to the requisite Dockerfiles in github.com/circleci-public/circleci-dockerfiles
> - PR should included logic to automatically deploy to GitHub Pages on every new commit to master

**Comment by iynere** [comment]
@felicianotech @glenjamin i vote we adapt this code for the new images, as well (https://hub.docker.com/r/cimg)

**Comment by glenjamin** [comment]
🎉 https://circleci.github.io/circleci-images/

**Comment by felicianotech** [comment]
@glenjamin This has been open for almost a year now. With the various image related parts we have in the works, I'm going to close this.

**Pull request closed without merging**
