### PR TITLE
golang: Add golangci-lint binary to image

### PR DESCRIPTION
**Pull request by hairyhenderson**
### Checklist
- [x] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary.
    - _n/a_

### Motivation and Context

[`golangci-lint`](https://golangci-lint.run/) is a popular linter used by many Go projects. The `cimg/go` image would be much more useful if it contained it.

I tested this by running the build and confirming the binary ends up in the right place.

### Description

Added the `golanci-lint` binary by copying it out of the upstream `golangci/golangci-lint` image. Note that it's pulling it from the alpine-based variant since that one is smaller, but the binary is statically-linked so there's no conflict with the `cimg/go` image being Debian-based.

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Review by pete-woods — COMMENTED** [review]
Usually it's better to version your build tool dependencies within your Go project (and have a make target install them).

This means that CI gives the same output as running the tool locally.

Adding this tool to the path in the CircleCI image could well impact all projects following this recommended pattern.

**Comment by hairyhenderson** [comment]
@pete-woods I suppose, though that adds to the build time - the reason for including in the image is to cut down on build time.

Doing this manually takes ~10s, so for a lint job that takes ~12s on its own, having to install it manually approximately doubles the CI time. Not a big deal, just thought this would be more convenient.

**Comment by pete-woods** [comment]
I'm a little surprised to hear those timings. The script we use to install golangci-lint and gotestsum takes less than 2 seconds, typically.

Let's talk about the version issue more, though. Where having a somewhat randomly pinned version of the linter gets downright infuriating if I build my software against a matrix of different versions of Go. This is extremely common for any serious Go library / app.

What is also common is to have linter exclusions and config, which is tied up with the version of the linter you're using that you want to work consistently across different Go releases (from each of the Docker images we offer).

If each Docker image ships with whatever was the current linter release at the time (I very much doubt we're going to rebuild every minor version of Go's Docker image each time golangci-lint releases), you're basically going to be in a constant battle with the linter for any decent sized project.

IMO if you want a consistent experience here, an optimal script embedded in an Orb would be a much better option. Downloading and installing a pre-compiled Go binary release from S3 inside our AWS infrastructure should take milliseconds. Even the approach we take on our projects where we `go install` them from source takes less than 2 seconds.

**Comment by hairyhenderson** [comment]
@pete-woods ok, no worries. I usually use custom Docker images for builds for my own personal projects, and I was setting up a new build for work and thought it might be useful to other users of `cimg/go` who want the linter as well. The precedent of having a specific version of `gotestsum` installed led me to believe this may be appropriate, but it's obviously not going to pass muster for this repo. No problem! I'll close the PR.

**Comment by pete-woods** [comment]
Please do consider contributing the same thing to the Go orb!

**Pull request closed without merging**
