### PR TITLE
add gnu make to basic dockerfile

### PR DESCRIPTION
**Pull request by willejs**
### Checklist
- [x] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary.

### Motivation and Context

I have included gnu make in all the images via the dockerfile basic template. Make is a common tool used in most build processes, and even this project uses it. 

### Description
added gnu make to apt-get install.

### CODE REVIEW

**Comment by felicianotech** [comment]
Hey @willejs,

Thank you for this PR. I'll look into the errors and try to get this merged today.

**Comment by iynere** [comment]
@willejs thanks for this. we've added make to the base image for our new prototype set of revamped convenience images, as well. you can check that out here if you're interested:

http://github.com/circleci-public/cimg-base

**Comment by willejs** [comment]
@iynere That looks really interesting, I didn't know that existed! 
I would switch to that but it does not include docker, which is a problem as we use that a lot in our tasks. So I don't think it is feasible for us to use that right now, or easily contribute to add it, but i am happy to contribute to that repo too in future.
@felicianotech @iynere do you think we can still merge this? Any idea on the test failures? I can dig into them if needed.

**Comment by felicianotech** [comment]
Working on it. It'll be merged.

**Comment by felicianotech** [comment]
Only PostgreSQL is failing. A fix for that has already been merged into staging. This is good to go.

**Comment by iynere** [comment]
@willejs we're adopting a newer pattern with the new images where we don't necessarily bake as many things into the image itself, and instead provide first-party orbs to install things at runtime. so, in this case, we've provided a Docker orb:

http://github.com/circleci-public/docker-orb

installing docker, docker-compose, & dockerize at runtime takes a negligible amount of time—plus, you can specify the exact versions you want, which is an improvement over hardcoding a particular version into the docker image

that said, docker tools are possibly commonly used enough that we actually _should_ bake them into the new images, so we'll look into that. shouldn't be too hard.

**Comment by willejs** [comment]
Thanks for the informative reply @iynere I am going to look at using that pattern too!

**Pull request merged**
