### PR TITLE
Update NDK to r20

### PR DESCRIPTION
**Pull request by Mygod**
Fixes https://github.com/circleci/circleci-images/issues/430. (hopefully)

### Checklist
- [ ] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [ ] I've updated the documentation if necessary.

### Motivation and Context

This PR relates to #430.

Why is this change required? What problem does it solve?
https://github.com/circleci/circleci-images/issues/430#issuecomment-522606940

Please describe in detail how you tested your changes.
I haven't. 😛 

### Description

NDK r17b -> r20

### CODE REVIEW

**Comment by felicianotech** [comment]
Reviewing

**Comment by felicianotech** [comment]
LGTM

**Comment by Mygod** [comment]
Yep. I can confirm this fixes #430 indeed.

**Comment by felicianotech** [comment]
Great to hear. Thanks.

**Pull request merged**
