### PR TITLE
Add MariaDB bundle.

### LINKED ISSUE #103: Add image for Mariadb?
Can you add a supported mariadb image? Given you have one for mysql already I wouldn't think this would be difficult.

Currently just using the default mariadb image increases our test run time by 3X because it's persisting data to disk.

https://discuss.circleci.com/t/tests-run-slower-on-2-0/12438

### PR DESCRIPTION
**Pull request by felicianotech**
### Checklist
- [x] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fixes #103 

### Description

Propose a MariaDB bundle.

### CODE REVIEW

**Comment by ryanwohara** [comment]
Oh, we did the same thing. RIP
https://github.com/circleci/circleci-images/tree/mariadb

I didn't open a PR because I didn't test the config. Do you know if that MySQL config works as-is for MariaDB?

**Comment by felicianotech** [comment]
Majority of it does. The specific settings we set in our template seem to from the research I did in the MariaDB docs.

I'm a casual MariaDB user and never had a MariaDB vs MySQL. I'm sure there will be edge cases but I figure we can tackle them if a MariaDB power user/veteran speaks up with any issue they run into.

**Comment by iynere** [comment]
LGTM 👍

**Comment by Geesu** [comment]
Should this be up on dockerhub? https://hub.docker.com/u/circleci/

**Comment by iynere** [comment]
@Geesu it is ! https://hub.docker.com/r/circleci/mariadb

**Pull request merged**
