### PR TITLE
Iynere remove dind

### PR DESCRIPTION
**Pull request by iynere**
### Checklist
- [X] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [n/a] I've updated the documentation if necessary.

### Motivation and Context

we've been building a docker-in-docker variant of our buildpack-deps image, aimed at customers hosting their own circleci installations, but folks on circleci.com are trying to use it & experiencing sadness :(

### Description

remove the dind variant

### CODE REVIEW

**Comment by felicianotech** [comment]
What's the status on this? I'm trying to use one of these variants now for a FOSS project I'm migrating to 2.0.

If we were to remove this, then I'd suggest we add `circleci/docker` as a 1st party image based on upstream `docker` so that people can still do DIND, maybe correctly?

**Comment by iynere** [comment]
@marcomorain @DanToml

**Comment by marcomorain** [comment]
I don't have the right context to review this. @DanToml ?

**Comment by iynere** [comment]
@felicianotech i would love to see a new PR for adding a Docker-in-Docker-compatible variant, if you can make it happen

**Pull request merged**
