### PR TITLE
Properly extract the Android NDK from the downloaded archive

### PR DESCRIPTION
**Pull request by freespirit**
### Checklist
- [x] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary.

### Motivation and Context

This PR relates to #228 - the `Android NDK` is not properly extracted. The build process expects to find the NDK tools directly inside `ANDROID_NDK_HOME` but the extract process puts them in a subdirectory of `ANDROID_NDK_HOME`.

Before I made this change all my builds (of an android project) were failing with an `NDK is missing a "platforms" directory.` message. After I added a job step that manually copies the content of the ndk subdirectory to the ndk directory itself all build were successful.

### Description
 The added support for `Android NDK` relies on a downloaded `.zip` file that is extracted and its content used for NDK builds. The problem in the mentioned issue is that the extracted content is actually unzipped in a subdirectory inside the `ANDROID_NDK_HOME`. E.g. if `ANDROID_NDK_HOME` is `/opt/android/ndk` then the `NDK` tools are unzipped inside `/opt/android/ndk/android-ndk-r17b/`. 

This change moves the tools one level up so they can be properly found inside `/opt/android/ndk/` (a.k.a. `ANDROID_NDK_HOME`) where the build tools expect them.

**Note:** It's probably much better to achieve the same with the extract tool itself (`unzip` or `tar`) but I can't find a straight-forward way yet. At least not with unzip.

### CODE REVIEW

**Comment by freespirit** [comment]
Regarding my last comment about achieving the same with the extract tool, I meant something like
`tar -xf /tmp/${ndk_version} -C ${android_ndk_home} --strip-components=1`

**Comment by iynere** [comment]
@freespirit thanks ! will take a look @ this later today

**Comment by ngriffiths** [comment]
If anyone else needs to work around this in the meantime, update the `image` in your `config.yml` to specify the hash of the image used on your last successful build: https://circleci.com/docs/2.0/circleci-images/#using-a-docker-image-id-to-pin-an-image-to-a-fixed-version

For example, I changed `circleci/android:api-27-alpha` to `circleci/android@sha256:b41c4a1aab6ae00a43351b126580bfda918d81c2b96f2b5f28b3e6c143a970bd`

**Comment by iynere** [comment]
@ngriffiths gonna merge this PR into our staging env & once the tests pass i will merge to master 🙏

**Comment by iynere** [comment]
@marcomorain can you approve this ? 🙏

**Comment by iynere** [comment]
👀 tysm !! @MonkeyTonk going to try & get this fixed before end-of-day

**Pull request merged**
