### PR TITLE
Switch to Debian Jessie Archive repo.

### LINKED ISSUE #366: OpenJDK 8 Can't Be Installed in -browsers variant
The OpenJDK 8 packages such as `openjdk-8-jdk` or `openjdk-8-jre` can't be installed in our `-browsers` variants anymore causing several jobs to fail.

The issue? On March 20th [Debian decided to move Wheezy and Jessie backport repositories to the archive](https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html). We are using the OpenJDK 8 packages from Jessie Backports.

I see three solutions for this.

1. Stop building Debian Jessie images. The main release of Debian 8 was EOL is 2018. While there still is the LTS project, it doesn't cover backports. https://wiki.debian.org/DebianReleases
2. We can switch to using the Jessie Backports Archive URL. This will then continue to work as expected, but packages in the Archive infrastructure are not maintained. This means no security updates at all.
3. We stop using OpenJDK 8 at all and use a newer version. OpenJDK is currently at v12, 8 is very old. This option isn't mutually exclusive to option 1.

I'll make PRs for the first two options and we can discuss from there which way to go.

### PR DESCRIPTION
**Pull request by felicianotech**
Fixes #366.

Please read through related issue ^ before commenting on this or merging.

### CODE REVIEW

**Comment by buitranquyet** [comment]
Our CircleCI builds are failing today due to this error:
Screen Shot 2019-03-26 at 8 50 56 AM

This might help fixing the issue?

**Comment by gapnav** [comment]
> Our CircleCI builds are failing today due to this error:
> Screen Shot 2019-03-26 at 8 50 56 AM
> 
> This might help fixing the issue?

I have same.
Sometimes I shows same IP addresses as on your screenshot, and sometimes - others
```
W: Failed to fetch http://http.us.debian.org/debian/dists/jessie-backports/main/source/Sources  404  Not Found [IP: 64.50.233.100 80]

W: Failed to fetch http://http.us.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found [IP: 64.50.233.100 80]
```

**Comment by felicianotech** [comment]
Hey everyone commenting here. This issue will be fixed today. If you don't want to wait, using the non-Jessie version of your image should avoid this issue entirely.

**Comment by dannyjeck-matroid** [comment]
Still seeing the issue: 

```

Starting container circleci/node:8.11.4
  image cache not found on this host, downloading circleci/node:8.11.4
8.11.4: Pulling from circleci/node
Digest: sha256:372dbff602066c00561c11b8a19d85665001b9c13ec82f87247e1910e9fbd63b
Status: Downloaded newer image for circleci/node:8.11.4
  using image circleci/node@sha256:372dbff602066c00561c11b8a19d85665001b9c13ec82f87247e1910e9fbd63b

```

With the same errors when trying to run `apt-get update`. Have the images being pulled not been updated yet?

**Comment by iynere** [comment]
hi @dannyjeck-matroid can you try one of the node tags that was built more recently ?

https://hub.docker.com/r/circleci/node/tags

**Comment by mazyvan** [comment]
I'm using `circleci/node:8.11.4` with out the "-jessie" suffix, and I'm having the same issue.

**Comment by iynere** [comment]
hi @mazyvan can you try one of the node tags that was built more recently ?

https://hub.docker.com/r/circleci/node/tags

**Comment by iynere** [comment]
i'm going to close this issue & redirect folks to the discuss post outlining the implementation of the fix:

https://discuss.circleci.com/t/convenience-images-update-changes-to-debian-mirror-for-browsers-tagged-image-variants

specifically:

> As a reminder, **we do not actively build/maintain [all available image tags ](https://circleci.com/docs/2.0/docker-image-tags.json)** . The tags we actively support are determined by the tags pushed to upstream Docker Library images, as outlined below:
> 
> * [https://github.com/circleci/circleci-images#official-images ](https://github.com/circleci/circleci-images#official-images)
> * [https://circleci.com/blog/build-image-update-schedule ](https://circleci.com/blog/build-image-update-schedule)
> 
> Thus, to ensure your image has the latest patch, make sure the tag you are using is a new one. You can easily make this determination in either of two ways:
> 
> * check the tags list at `https://hub.docker.com/r/circleci/YOUR_IMAGE/tags` , which lists tags by last-pushed date
> * check [our `circleci-dockerfiles` repository ](https://github.com/circleci-public/circleci-dockerfiles), which publishes complete Dockerfiles for all tags published as part of each new commit to [our images repository ](https://github.com/circleci/circleci-images)
> 
> You can also use our images’ semantic versioning system, which draws from the semantic versioning of upstream Docker Library images, to make sure you receive these kinds of updates automatically. For example, while the `circleci/node:9.10.0` image tag may not be built in the future, referencing `circleci/node:9.10` in your `config.yml` file will ensure that you always receive the latest `circleci/node:9.10.z` image tag.

**Pull request merged**
