### PR TITLE
Updating Node variants to current LTS, 10.

### PR DESCRIPTION
**Pull request by felicianotech**
The Node LTS has been bumped from Node.js v8 to v10. We're a few weeks behind on this but this completes that update on our end.

### CODE REVIEW

**Comment by phawxby** [comment]
I think this should probably been communicated a bit better. 

We've got apps that run on the PHP image but do other tasks (js/sass  compile, deployment, etc) based on node scripts. We're encountering dependencies which aren't ready for V10 and suddenly started breaking.

**Comment by felicianotech** [comment]
@phawxby,

Do you have any suggestions on how this can be improved? Node.js v10 has been out for 7 months already and is now the current LTS version. The Node variant images use Node.js LTS.

We've also blogged about it a month ago ([link](https://circleci.com/blog/nodejs10-lts/)) and I posted it in the announcement section of our forums this morning ([link](https://discuss.circleci.com/t/convenience-image-node-variants-updated/26834)).

During the release, Node.js itself mentioned that this switch would be happening in October. We were actually late publishing the change ([link](https://nodejs.org/en/blog/release/v10.0.0/)).

**Comment by iynere** [comment]
@phawxby if you need older node, you can always split your node work into separate circleci jobs that use our node images, which, of course, let you pick exactly the version of node that you need

**Comment by phawxby** [comment]
@felicianotech the support forum isn't somewhere I really browse unless I need support. Fair point about the blog though, I've subscribed that my own fault for not being subscribed.

It might be good if major changes and upcoming major changes where displayed in the CircleCI dashboard. It would've saved me time looking for outages, bad changes causing things to fail, etc. 

Good idea @iynere, I'll try to fix things first and if not break it into a separate job.

**Comment by iynere** [comment]
@phawxby also, long term, we'll be looking to install `nvm` in our `-node`-tagged image variants, so folks can choose themselves 🙂

**Pull request merged**
