### PR TITLE
Remove offline google maven repositories

### PR DESCRIPTION
**Pull request by joshfriend**
### Checklist
- [X] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [X] I've updated the documentation if necessary.

### Motivation and Context

The android images are currently almost 3GB in size. I would like them to be smaller, especially since the circleci image collection is pushed every few days.

### Description

Google moved their support library, firebase, and google play services artifacts to an [online maven repo](https://developer.android.com/studio/build/dependencies#google-maven). Users with a reasonably up-to-date build process and dependency tree will have no need for the offline copy.

* The offline copy that is installed with `sdkmanager extras;...` has no versions of firebase or play services newer than 11.0.0 (Current is 15.x or something though they skipped 13/14).
* The online maven repo has support library versions dating back to 18.0.0
* Newer versions of the android gradle plugin understand the `google()` repo directive, but older ones that don't can use `maven { url: 'https://maven.google.com' }`
* The `extras;google;google_play_services` repo in particular has no actual maven artifacts and only contains documentation and example code, which is useless in a CI build environment.

With these changes and the proposed use of slim JDK in #201, the image size goes from ~2.9GB to just ~930MB.

### CODE REVIEW

**Comment by marcomorain** [comment]
Hi @joshfriend - thanks for this, it's awesome.

Do you know what changes people would need to make to their apps for this to work, or do you tihnk the chance is backwards compatible?

**Comment by joshfriend** [comment]
I'd also add that the lowest android sdk level supported by the circleci images is 23, which in the android world is pretty recent, so it seems likely to me that anyone using these images would be up-to-date, or could be with minimal effort.

**Comment by joshfriend** [comment]
My android dev team has been using a fork of the circle-ci images with these changes since I proposed them and have had no issues.

@marcomorain do you have any objections or concerns about the changes?

**Comment by iynere** [comment]
@joshfriend this is amazing, thanks so much!

let me wait until i get https://github.com/circleci/circleci-images/pull/226 merged, and then i'll either merge this one or make the equivalent code changes in a separate PR

&, on a higher level, we are also revising code-ownership of this repository (see https://github.com/circleci/circleci-images/pull/227), so that development on this repository can move forward more quickly

**Comment by joshfriend** [comment]
Excellent, thanks! I'll keep an eye on #228, this branch will likely need a rebase after that is merged (unless you get to it first).

**Comment by iynere** [comment]
gonna hold off on merging this PR until we get some clarity on messaging around possible breaking changes @joshfriend i agree with you that this change makes sense, but we should let folks know that they may need to update their projects [as you described](https://github.com/circleci/circleci-images/pull/202#issuecomment-390706253)

**Comment by tkhduracell** [comment]
👍

**Comment by ryanwohara** [comment]
This looks like a good change for us to schedule merging in early October.

**Comment by iynere** [comment]
@joshfriend finally getting this merged, thanks for your patience !

**Comment by joshfriend** [comment]
Woohoo! Today is gonna be a good day 😄 

Thanks everyone!

**Pull request merged**
