### PR TITLE
Feature/ndk

### PR DESCRIPTION
**Pull request by gengjiawen**
### Checklist
- [x] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary.

### Motivation and Context

https://github.com/circleci/circleci-images/issues/73

### Description

Add ndk support. I am not familiar with bash or m4, so there maybe some silly mistakes, hope it helps.
The generated `api-27-node8-ndk-alpha` is 7.65GB on my ubuntu 16.04.

### CODE REVIEW

**Comment by marcomorain** [comment]
Thanks for the PR. I’ll look At this on Monday 👍

**Comment by gengjiawen** [comment]
@marcomorain Do you have time to review this ?

**Comment by matteblair** [comment]
I would also appreciate NDK images for my project! There are other Android images with the NDK floating around Dockerhub, but it would be nicer to have it in an official, pre-cached CircleCI image.

**Comment by marcomorain** [comment]
Sorry for the delay - I'm testing this out now, a lot later than I had intended.

**Comment by marcomorain** [comment]
Installing the NDK seems to have ballooned the image size to nearly 8gb (from 2gb, afaik). Is it really that large? 

Do you know if there is anything we can strip from it?

**Comment by gengjiawen** [comment]
I don't know it's still this large when you push to dockerhub. I have an android-ndk image, which is only 3GB https://hub.docker.com/r/gengjiawen/android-ndk/~/tags/.

**Comment by ryanwohara** [comment]
This would be nice to have but I need to close this PR as it's been inactive for a few months.

**Comment by gengjiawen** [comment]
So why not find someone give this pr a serious review instead of close it.

**Pull request closed without merging**
