### PR TITLE
Add Android API 29

### PR DESCRIPTION
**Pull request by felicianotech**
Adds the Android Q API level, 29. Also adds build-tools v29.0.0.

### CODE REVIEW

**Comment by joshuamking-driveclutch** [comment]
So this is in staging now, is there a way I can access that, or do I need to wait til it's in prod? Thanks

**Comment by iynere** [comment]
@joshuamking-driveclutch you should be able to access all the images published from staging, they are at hub.docker.com/r/ccistaging

that said, we certainly can't recommend using the staging images—however, feel free to give one a shot. we'll get this merged to master ASAP—thanks!

**Comment by iynere** [comment]
@joshuamking-driveclutch we're going to wait until sunday / monday to merge to master, to avoid the possibility that something breaks over the weekend. appreciate your patience !

**Comment by joshuamking** [comment]
Completely understand that, thanks for the heads up! 👍

**Pull request merged**
