### PR TITLE
Add support for API 27

### PR DESCRIPTION
**Pull request by ronocod**
### Checklist
- [ ] I've run `make` from the root directory to see all Dockerfiles are created successfully. 
_I've run `generate-images` in the `android` directory and `docker build .` from `android/images/api-27-alpha` successfully. Can do this whole step if you want.
- [x] I've updated the documentation if necessary.

### Motivation and Context

Android API 27 is out, as well as Build Tools 27.0.0. We'd like to use these in our project.

### Description
Based on https://github.com/circleci/circleci-images/pull/88, I've added the new Build Tools, and I've added 27 to the list of API version that images are generated for.

### CODE REVIEW

**Comment by marcomorain** [comment]
Thanks!

**Comment by marcomorain** [comment]
We build every night, so this will show up tomorrow under the circleci org, and in about 20 minutes here: https://hub.docker.com/r/notnoopci/android/

**Comment by ronocod** [comment]
Great, thanks!

**Comment by marcomorain** [comment]
Thanks again @ronocod

**Pull request merged**
