### PR TITLE
try including alpine variants for node

### PR DESCRIPTION
**Pull request by iynere**
### Checklist
- [X] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [X] I've updated the documentation if necessary.

### Motivation and Context

This PR relates to https://github.com/circleci/circleci-images/issues/390.

we include logic for deciding whether or not to build alpine variants, if they exist in the upstream community image, for a given language/framework. let's see if it can generate working alpine node images for us.

### Description
set `INCLUDE_ALPINE: true` for node

### CODE REVIEW

**Comment by iynere** [comment]
@phawxby can you try one of the alpine images from this commit & let us know if it works for you ? that won't necessarily be enough confirmation for us to merge into master, but will at least let us know we're on a good track:

https://github.com/CircleCI-Public/circleci-dockerfiles/tree/node-alpine/node/images/6.17.1-alpine
https://github.com/CircleCI-Public/circleci-dockerfiles/tree/node-alpine/node/images/8.15.1-alpine
https://github.com/CircleCI-Public/circleci-dockerfiles/tree/node-alpine/node/images/10.15.3-alpine
https://github.com/CircleCI-Public/circleci-dockerfiles/tree/node-alpine/node/images/11.14.0-alpine

any of the dockerfiles in those directories exist as callable tags on the `ccitest` docker hub org:

https://hub.docker.com/r/ccitest/node

so, e.g., `ccitest/node:8.15.1-alpine`, or `ccitest/node:11.14.0-alpine-browsers`, etc. 🙏

**Comment by phawxby** [comment]
Amazing! I'll give these a test and let you know!

**Comment by iynere** [comment]
thank you !! @phawxby

**Comment by phawxby** [comment]
Am I having a dim moment?

```
Build-agent version 1.0.10495-4fff0daa (2019-04-15T10:44:03+0000)
Docker Engine Version: 17.05.0-ce
Kernel Version: Linux 94f81a215743 4.4.0-144-generic #170~14.04.1-Ubuntu SMP Mon Mar 18 15:02:05 UTC 2019 x86_64 Linux
Starting container ccitest/node:10.15.3-alpine
  image cache not found on this host, downloading ccitest/node:10.15.3-alpine

Error response from daemon: manifest for ccitest/node:10.15.3-alpine not found
```

**Comment by iynere** [comment]
@phawxby nope, def not, something curious going on, let me dig in....

**Comment by iynere** [comment]
hmmm, altho we definitely generated alpine dockerfiles, we don't appear to have built images from them @phawxby gonna try to fix

**Comment by iynere** [comment]
ah, as i suspected, it's not quite so simple @phawxby 

previously, we were just generating the alpine variant dockerfiles, but not actually building them. with the new commit i pushed, we're attempting to build alpine variants of the node image, but, as you can see from the CI checks, it's not working. & i confirmed by trying to build [this Dockerfile](https://github.com/CircleCI-Public/circleci-dockerfiles/tree/node-alpine/node/images/10.15.3-alpine) locally, as well :/

i think we have some logic in our dockerfiles that still assumes various environmental things that don't apply to alpine, unfortunately, so this will be a longer-term effort for us

going to close my PR, as i don't think this will be the approach we'll take, but in the interim, i think everything i said here still stands as a good summation of the issue:

https://github.com/circleci/circleci-images/issues/390#issuecomment-483353451

**Comment by phawxby** [comment]
Ah nuts. Thanks for trying! 

If you're already working on updated convenience images I can understand why you'd not want to spend much time on this. I'll give one of your other suggestions a go as a temporary measure.

**Pull request closed without merging**
