### PR TITLE
postgis scripts need to be executables

### PR DESCRIPTION
**Pull request by notnoopci**
### Checklist
- [ ] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Postgis scripts need to be executables 

This PR relates to #122

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
When are those images expected to be available? Looks like the master build step finished, but we are still seeing this issue.

**Comment by browniebroke** [comment]
I think you can follow the builds on [the CI](https://circleci.com/gh/circleci/circleci-images).
They have been some [recent pushes on Dockerhub](https://hub.docker.com/r/circleci/postgres/tags/), but that might be the previous commit?

**Comment by johanneswuerbach** [comment]
Then this seems to not fix the issue:
```
$ docker pull circleci/postgres:9.4-postgis-ram
...
Digest: sha256:d07eeff48a2ac1f3b788341e61075fb72cc83d69a2ecaf19eb37e809646ca2dc
Status: Downloaded newer image for circleci/postgres:9.4-postgis-ram
```

```
$ docker run -it circleci/postgres:9.4-postgis-ram
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
...
CREATE DATABASE

CREATE ROLE


/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/postgis.sh
/usr/local/bin/docker-entrypoint.sh: line 128: /docker-entrypoint-initdb.d/postgis.sh: Permission denied
$ echo $?
1
```

**Comment by browniebroke** [comment]
Maybe better to follow up in #122?

**Comment by notnoopci** [comment]
Thanks - I'm working on this now and I'll update you when it's fully fixed.  Also, there is a bit of delay from container images creation to it being used due to some caching effects on our end for our convenience images - I'll let you know when it's fully fixed.  Thanks for your patience.

**Comment by notnoopci** [comment]
Please note that in the mean time, you can pin the image to a working one by specifying the sha, e.g. `circleci/postgres@sha256:6125f3d92634a0c0a99a0d864c768a9187dd1e03fef7a09d66856bf69cda4ed4` which you can see in previous successful builds under `Spin up Environment` step:

```
Starting container circleci/postgres:9.4-postgis
  using image circleci/postgres@sha256:6125f3d92634a0c0a99a0d864c768a9187dd1e03fef7a09d66856bf69cda4ed4
```

**Pull request merged**
