### PR TITLE
Android: Update Ruby version to 2.6.0

### PR DESCRIPTION
**Pull request by rye**
### Checklist
- [x] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary. (Don't think it was necessary.)

### Motivation and Context

This PR doesn't have a corresponding issue.

The new version of Ruby was released a few days ago, and includes a large number of speed gains and new low-level features I'd like to be able to use.

I would understand if this is too much of a jump, but since 2.6.0 is semver-backwards-compatible with 2.4.3, I would think it shouldn't be too scary.  Also, Ruby 2.4.3 is no longer the latest 2.4 release, so if 2.6 is too far of a jump I'd like to consider moving to 2.5.3 (latest 2.5) or 2.4.5.

I have tested this locally with a full `fastlane` suite on a React-Native codebase. Fastlane is a common Ruby-based build script in Android, and it worked fine.

### Description

`s/2\.4\.3/2\.6\.0/g` in `Dockerfile.mk`. See diff. (It's a one-liner.)

### CODE REVIEW

**Comment by iynere** [comment]
hi there @rye 

first of all, thank you !

this seems pretty reasonable. usually, we would want to message in advance about version bumps like this, but seeing as it's in our android image, rather than the main ruby images themselves, i don't thiink there's much of an expectation that folks will be receiving some particular version of ruby

let's just wait til after new year's so other folks can weigh in, but then we can likely get this merged quickly. for now, i'll merge to staging, so we can see if the images build ok

**Comment by rye** [comment]
Thanks, @iynere!

No rush on shipping this. Feel free to make any additional updates necessary to get this to your liking. And yes, my apologies that I didn't open an issue first—it seemed like a small enough thing that I could just PR it as-is.

Let me know if you need anything else from me!

**Comment by felicianotech** [comment]
Hi @rye,

I think we waited a bit too long after New Years. :)

Would you be able to bump Ruby to v2.6.1 so I can get this merged?

**Comment by rye** [comment]
@felicianotech absolutely! Just a moment.

**Comment by rye** [comment]
@felicianotech actually, I think I deleted the fork this was pulled from by accident when I was doing a monthly purge of forks. I will have to make another PR for the next update, which I will do.

**Pull request closed without merging**
