### PR TITLE
Upgrade to Android NDK r18b

### PR DESCRIPTION
**Pull request by guillaume-tgl**
### Checklist
- [x] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary.

### Motivation and Context

This PR relates to #302 .

This is the new standard version of the NDK.

### Description
Upgrade to the latest version of the NDK.

### CODE REVIEW

**Comment by iynere** [comment]
thank you ! @guillaume-tgl 

i will dig into your PR tomorrow—i saw that all your circleci jobs failed & was motivated to fix that problem : https://github.com/circleci/circleci-images/pull/305

once i get that merged, you'll be able to actually see jobs / tests run on your PRs to this repo 🎉

**Comment by iynere** [comment]
@guillaume-tgl ok, finally got the repo into a place where forked PRs will build / test successfully—your modified android images are being built / tested here : 

https://circleci.com/gh/circleci/circleci-images/14862

**Comment by guillaume-tgl** [comment]
Any update on this PR? Is there anything missing? NDK r19b is already out :)

**Comment by iynere** [comment]
thanks for the reminder ! @guillaume-tgl 

we'll get to this next week

**Comment by elevenfive** [comment]
I opened a PR for r19c since that is out.  I also added SHA-256 checking.  I don't mind closing if this PR supercedes my changes.  Thanks for working on this!

https://github.com/circleci/circleci-images/pull/353

**Comment by iynere** [comment]
closing this as we have a newer PR & may take a more general approach anyway

**Pull request closed without merging**
