### PR TITLE
add node variants to elixir & python

### PR DESCRIPTION
**Pull request by igalic**
- [x] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary.

The elixir community, especially the Phoenix part thereof, heavily relies on
node and other tools written in Javascript. 

This PR relates to (and closes) #90 & #58.

we move the ruby & php "specific" code into generate.sh and generate node and
browsers, node & node-browsers images for elixir and python.

### CODE REVIEW

**Comment by DanToml** [comment]
Thanks - this looks great 👍

**Comment by igalic** [comment]
how long until these images will be available on docker hub?

**Comment by DanToml** [comment]
@igalic they should be available as [this workflow](https://circleci.com/workflow-run/8692a518-1c12-483b-a175-695652ce51c3) completes

**Comment by igalic** [comment]
screenshot_2017-10-24-11-14-28-100

that work flow is either not available to outside users, or in mobile, or maybe i just have to login, or maybe i should stop checking github on my phone 😅

**Pull request merged**
