### PR TITLE
Update Android NDK to r19c

### PR DESCRIPTION
**Pull request by elevenfive**
- Use r19c, released Jan 2019
- Was on old version r17b from mid 2018
- https://developer.android.com/ndk/downloads/revision_history

### Checklist
- [x ] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x ] I've updated the documentation if necessary. (Not needed, no references to NDK version found)

### Motivation and Context

This PR relates to keeping the Android build toolchain up-to-date with official releases from Google.

Rather than forcing developers to download the latest NDK on their own, use a pre-baked version of the latest NDK.

### Description
- Use new NDK version
- Check SHA-256 hash of downloaded NDK for additional security

### CODE REVIEW

**Comment by iynere** [comment]
to make this easier, i'm creating an orb so you can easily install whatever NDK version you want at runtime @elevenfive

**Comment by iynere** [comment]
@elevenfive not sure if this will be the final implementation, but for now, you can install any version you like this way : 

https://github.com/cci-orbs/circleci-images

**Comment by iynere** [comment]
@elevenfive ok to close this PR ? thanks so much for the PR to the orb !

**Comment by elevenfive** [comment]
Closing in favor of orbs

**Pull request closed without merging**
