### PR TITLE
Add mill tool to openjdk

### PR DESCRIPTION
**Pull request by nvander1**
### Checklist
- [x] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary. (Not necessary in this case).

### Motivation and Context

This will give circleci users who use java/scala access to [mill](https://github.com/lihaoyi/mill) by default.

### Testing
Run this from openjdk/images after running `make` from the root. (Note that if you have any existing docker images starting with `mill-` this will not be correct.
```bash
#!/bin/bash
export folders=`ls -d */`
export num_folder=`ls -d */ | wc -l`

export function build_images {
  for folder in $folders; do
    tag=${folder::-1}
    docker build -t mill-$tag ./$folder
  done
}

export function check_builds {
  built_images=`docker images | grep mill- | wc -l`
  echo "Built $built_images/$num_folder"
}

build_images
check_builds
```

### Description

This modifies the generation of the openjdk image to include the latest version of mill.

### CODE REVIEW

**Comment by nvander1** [comment]
@eddiewebb Is the project currently accepting pull requests?

**Comment by nvander1** [comment]
@iynere
Hi! What can I do to help move this along? c:

**Comment by iynere** [comment]
hi @nvander1, apologies for the delay. quick question—how long does it take to install mill at runtime?

if it only takes a few seconds, i'd suggest creating an orb to simplify the mill installation process, rather than baking another tool into the image itself

**Comment by nvander1** [comment]
Thanks for the reply @iynere. As it turns out, there is an existing docker image that includes the JDK + mill on docker hub.

**Pull request closed without merging**
