### PR TITLE
Add postgres 11

### PR DESCRIPTION
**Pull request by iynere**
### Checklist
- [X] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [X] I've updated the documentation if necessary.

### Motivation and Context

follow-up on this PR https://github.com/circleci/circleci-images/pull/306

### CODE REVIEW

**Comment by iynere** [comment]
@bgentry

**Comment by bgentry** [comment]
Dug through the log file, could only find these errors:

```
9.6.11-postgis-add-postgres-11-ba0206a2cb1c: digest: sha256:7ce660bb0973e62f0f4a6778ac32cb687c1b8418060896dbb05199c70dfbb017 size: 4286
handling alias 9.6-postgis
The push refers to a repository [docker.io/ccitest/postgres]
Get https://registry-1.docker.io/v2/: EOF
make[1]: *** [postgres/images/9.6.11/postgis/publish_image] Error 1
make[1]: Leaving directory `/home/circleci/circleci-bundles'
```

And then at the end of the build:

```
9.5-alpine-postgis-ram-add-postgres-11-ba0206a2cb1c: digest: sha256:bea7bee48670b5c4cb6ae5fcafa8baac1c45e413efa0073cf995f71746067a88 size: 3233
Untagged: ccitest/postgres:9.5-alpine-postgis-ram-add-postgres-11-ba0206a2cb1c
Untagged: ccitest/postgres:9.5.15-alpine-postgis-ram
~/circleci-bundles
make[1]: Leaving directory `/home/circleci/circleci-bundles'
make: *** [postgres/publish_images] Error 123
Exited with code 2
```

No idea on the cause though 😞

**Comment by iynere** [comment]
hmm, thank you ! @bgentry 

[the `example` tag's Docker Hub automated build](https://hub.docker.com/r/ccitest/postgres/builds) may offer more guidance—it will be direct `docker build` output w/o any output swallowed by `make`. it's pending / queued rn but will take a look as soon as it's in-progress.

**Comment by iynere** [comment]
@bgentry do you specifically need postgres 11 with postgis ? i just noticed we already are building postgres 11 images : 

https://hub.docker.com/r/circleci/postgres/tags?page=2

https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/postgres/images/11.1
https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/postgres/images/11.1-alpine

**Comment by bgentry** [comment]
> do you specifically need postgres 11 with postgis ?

Yeah, thanks for checking but that's what we need. RAM disk doesn't matter but figured it's faster.

Obviously if there are real failures or blockers to merging this then do it on whatever schedule you need, I can figure out an alternative if necessary! And lmk if there is in fact something I can do to help move it forward (such as building an image locally).

**Comment by bgentry** [comment]
I also pushed the v11-postgis-ram variant to DockerHub on our org as `distru/postgres:11.1-alpine-postgis-ram`, and completed a CircleCI build with it successfully. Anyway, lmk if there's a specific one failing that I can look into :v:

**Comment by iynere** [comment]
@bgentry yup, things look good on our end too—the automated build with your changes was successful: https://hub.docker.com/r/ccitest/postgres/builds

**Comment by bgentry** [comment]
@iynere yay, thanks! 🙏

**Pull request merged**
