### PR TITLE
re-enable PostGIS with Postgres v11

### PR DESCRIPTION
**Pull request by bgentry**
### Checklist
- [x] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [ ] I've updated the documentation if necessary. (not necessary afaict)

### Motivation and Context

I wanted to get our app updated to Postgres v11. I discovered that many of the CircleCI docker images I expected to find did not exist for v11 or v11.1.

While digging into this, I noticed that some Postgres v11 variants [were commented out](https://github.com/circleci/circleci-images/blob/4a6278445b8865e360216ab089ce7f5dbd91e870/postgres/generate-images#L21-L26). In particular, the `alpine-postgis-ram` variant. The note appears to no longer apply, so I've removed that special handling.

I ran `make` and confirmed that the images generate. I do not know whether they actually build properly, though. Maybe somebody on the team there wants to try running this through the normal build process?

### Description

I commented out the special handling that excluded postgis RAM variants.

### CODE REVIEW

**Comment by bgentry** [comment]
Not sure what's up w/ this CI failure but it doesn't seem like something I can resolve:

```
 create mode 100644 golang/images/1.11.4/node-browsers/Dockerfile
 create mode 100644 golang/images/1.11.4/node/Dockerfile
 create mode 100644 postgres/images/11.1-alpine/postgis-ram/Dockerfile
 create mode 100644 postgres/images/11.1-alpine/postgis/Dockerfile
 create mode 100644 postgres/images/11.1/postgis-ram/Dockerfile
 create mode 100644 postgres/images/11.1/postgis/Dockerfile
ERROR: Permission to CircleCI-Public/circleci-dockerfiles.git denied to testcheckoutkey.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Exited with code 128
```

**Comment by iynere** [comment]
@bgentry i've just merged a PR to staging so that forked PRs will build / test successfully & you won't run into those issues : https://github.com/circleci/circleci-images/pull/305

i've rebased your PR, so your tests should run now

**Comment by iynere** [comment]
ahh, still one bug to address here—will need to make some changes. i'd like for your PR to be tested successfully, so let me try to get this fixed before we look at your changes here.

**Comment by bgentry** [comment]
Hmm, I also rebased on `staging` manually but same failure. Ping me if you want me to make any other changes!

**Comment by iynere** [comment]
@bgentry ok, i _believe_ i've removed all the roadblocks here—our build control flow compares the current to the most recent commit & only builds a particular image if certain relevant files were modified between those commits (which now is not the case, given all the fixing i've done)—in short, can you trigger a new cosmetic commit to the `postgres/generate-images` file? can just be a simple comment or something.... thank you !!

**Comment by bgentry** [comment]
@iynere done, looks like it's passing now :v:

**Comment by iynere** [comment]
@bgentry ahh, it's passing, but the images did not actually build. i need to fix a bug in our commit-comparing logic. will probably just set it to always build all images on forked PRs. thanks for your patience !

**Comment by iynere** [comment]
@bgentry ironically, your seemingly cosmetic commit actually was not cosmetic, due to some `sed` commands....

anyway, i think i have FINALLY fixed this for real, your modified postgres images are now actually  building:

https://circleci.com/gh/circleci/circleci-images/14847

**Comment by iynere** [comment]
@bgentry looks like the postgres job is failing now, [this may be the culprit](https://github.com/circleci/circleci-images/pull/306/files#diff-e322ccee7ce8e94528b6e5f85f14d290):

> PostGIS v2.4.4 is failing to compile with PG11 causing the apt package	
> potgresql-11-postgis-2.4 to not be available, failing builds. **The v2.5.0	
> release of PostGIS will fix this, which will also cause a new apt package	
> name. We'll need to tackle that issue once PostgreSQL 11 is released.**

if you can figure out what the new apt package name is, feel free to push a new commit to your fork/branch 🙏

**Comment by bgentry** [comment]
Looks like the new package is called `postgresql-11-postgis-2.5` and the postgis [version is 2.5.1](https://www.ubuntuupdates.org/package/postgresql/xenial-pgdg/main/base/postgresql-11-postgis-2.5). I updated that here, lmk if I need to do anything to re-trigger the image builds.

**Comment by iynere** [comment]
hmm, the job is still failing @bgentry https://circleci.com/gh/circleci/circleci-images/14922

let me know if you're able to debug anything—otherwise, i will take a look tomorrow, thank you !

**Comment by bgentry** [comment]
@iynere it appears that building `ccitest/postgres:11.1-alpine-postgis` succeeeds, but then later it attempts to build the postgis-ram version of that and fails because that previous image is not published to DockerHub:

```
./shared/images/build.sh ./postgres/images/11.1-alpine/postgis-ram/Dockerfile
~/circleci-bundles/postgres/images/11.1-alpine/postgis-ram ~/circleci-bundles
Building docker image from ./postgres/images/11.1-alpine/postgis-ram/Dockerfile
OFFICIAL IMAGE REF: ccitest/postgres:11.1-alpine-postgis-ram
Error response from daemon: manifest for ccitest/postgres:11.1-alpine-postgis-ram not found
image is a variant image
Sending build context to Docker daemon  4.096kB


Step 1/2 : FROM ccitest/postgres:11.1-alpine-postgis
manifest for ccitest/postgres:11.1-alpine-postgis not found
retry building ccitest/postgres:11.1-alpine-postgis-ram
Sending build context to Docker daemon  4.096kB


Step 1/2 : FROM ccitest/postgres:11.1-alpine-postgis
manifest for ccitest/postgres:11.1-alpine-postgis not found
make[1]: *** [postgres/images/11.1-alpine/postgis-ram/publish_image] Error 1
make[1]: Leaving directory `/home/circleci/circleci-bundles'
make[1]: Entering directory `/home/circleci/circleci-bundles'
```

**Comment by iynere** [comment]
ahhh, of course, good catch @bgentry 

hmm, let me think about a solution here.... i want to find a secure way to give external contributors the ability to push images to our docker hub test env, i think that would be easier than trying to modify our image logic to not have a dependency on docker hub in that way

**Comment by bgentry** [comment]
@iynere just curious, is there anything that can be done to move this along in the shorter term without blocking on these build process improvements? i.e. manually pushing that first dependent image, or having you push it instead?

I'd really like to get our app's CI migrated to Postgres v11 😬

**Comment by iynere** [comment]
@bgentry i think you could fairly easily manually build & push a modified version of the image w/ postgres 11 to your own docker hub env

**Comment by iynere** [comment]
making this repository accessible to community contributions is super important & unfortunately you're simply exposing a lot of pain points that we still need to improve for folks....

**Comment by iynere** [comment]
in the short term, i can create a branch on this repo & merge this PR into the branch, that will cause all the images to build, test , & push successfully. (i probably should have done that earlier, but i really wanted to get all these bigger issues resolved once and for all.) thank you for your patience ! @bgentry

**Comment by iynere** [comment]
for sure i hear you 😄

**Pull request merged**
