### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by pranjalv9**
updated year 2017 -> 2019 in license file

### Checklist
- [ ] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary.

### Motivation and Context

This PR relates to <issue>.

### CODE REVIEW

**Comment by felicianotech** [comment]
Hi @pranjalv9,

If we're going to update the copyright date, can you make it "2017-2019" instead of just 2019 please?

**Comment by pranjalv9** [comment]
@felicianotech please let me know if any other change is required

**Comment by felicianotech** [comment]
If you take a look at the "Files Changed" tab on GitHub nothing shows up. I think you undid your change when you merged in the `master` branch which shouldn't have been merged. The default branch for this repository is `staging`.

**Comment by felicianotech** [comment]
Closing since there's no response.

**Pull request closed without merging**
