### PR TITLE
Make sure PATH includes ~/.local/bin

### LINKED ISSUE #375: Request: Add ~/.local/bin to default PATH?
Background: https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#~/.local/bin/

A number of developments tools (such as `pip install --user`) will use the `~/.local` prefix and install executables into `~/.local/bin`, which is part of the default PATH on many modern operating system distributions.

It would be great if the CircleCI images include this by default, so that jobs can make use of it without having to manually add the missing PATH entry first.

### Upstream Debian bug

* [#839155 - bash: $HOME/.local/bin missing from $PATH again - Debian Bug report logs](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839155)

Debian fixed this, but it's not in the Debian stretch release that's used by the upstream Docker images.

However, waiting for this upstream fix to reach the CircleCI images won't quite be enough, either, because the fix only adds the path entry if the directory already exists. This conditional logic may make sense for Debian's default interactive user experience, but it means the PATH entry will still be missing for new CircleCI containers. So, this should still be worth addressing in the CircleCI base images.

### PR DESCRIPTION
**Pull request by PiDelport**
### Checklist
- [ ] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x] I've updated the documentation if necessary.

### Motivation and Context

This PR relates to <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839155>, and should resolve #375 (see there for discussion).

### CODE REVIEW

**Comment by iynere** [comment]
@PiDelport when i merge this to staging, it will generate staging images here: 

https://hub.docker.com/u/ccistaging

can you then try a job w/ one of those images (you can find all tags built from the commit in question here: https://github.com/CircleCI-Public/circleci-dockerfiles/commits/staging) & let us know on this PR if it actually works ?

just wanna make sure we don't do something when spinning up containers for folks' jobs that doesn't, like, overwrite `PATH` somehow....

thanks for your PR !!

**Comment by PiDelport** [comment]
@iynere: Ah, it looks like this is not quite enough after all: the shell only reads `.profile` for _login_ shells.

```shell
# interactive:
$ rundocker ccistaging/python:3.7 sh -c 'echo $PATH'
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# login:
$ rundocker ccistaging/python:3.7 sh -l -c 'echo $PATH'
/home/circleci/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

(same for `bash`)

**Comment by iynere** [comment]
correcttttt @PiDelport https://circleci.com/docs/2.0/configuration-reference/#default-shell-options

**Comment by iynere** [comment]
@PiDelport can you submit a new PR & use Dockerfiles' `ENV` syntax to do this ? i _thiink_ that should work

https://docs.docker.com/engine/reference/builder/#env

**Comment by PiDelport** [comment]
Hmm, using `ENV` as an override outside the container may not be that straightforward:

* It overrides the container's original `PATH` value, which could be error-prone: different base images could make different choices and assumptions about their default system paths.
* Overriding it at the Docker level isn't aware of what user inside the container things end up being executed as: we don't want `/home/circleci/.local` in the path when executing as root or any other account.

The standard approach above takes care of all of this: I don't think it'll be easy to go outside of that without affecting the relative neutrality that the base images should have.

**Comment by PiDelport** [comment]
@iynere: This PR combined with defaulting to a login shell seems to make things work as expected! :tada:

Successful build: dfaff69 (https://circleci.com/gh/OpenUpSA/khetha-django/159)

I think that changing the default shell values to be login shells should be the correct solution to go forward with: I don't think this is the only thing that assumes Unix login semantics for setting up the initial environment, paths, and so on.

**Comment by PiDelport** [comment]
I searched around to see what decisions other CI communities have made regarding this, and it seems that GitLab has run into this with RVM (which only activates in login shells), and changed their default shells to be login shells:

* https://gitlab.com/gitlab-org/gitlab-runner/issues/86
* https://gitlab.com/gitlab-org/gitlab-runner/issues/87

It looks like CircleCI has also run into this issue before too:

* https://medium.com/@odedre/circle-ci-v2-react-native-project-build-release-setup-ce4ef31209d0

```
  # use a --login shell so our "set Ruby version" command gets picked up for later steps
  shell: /bin/bash --login -o pipefail
  steps:
    …
```

**Comment by PiDelport** [comment]
Should I open a new issue to propose adding `--login` to the default shell values?

**Comment by iynere** [comment]
@PiDelport lol if you want to fight that fight, i definitely support it, but i can't guarantee your success... there's not even an open-source repo you could file a PR or issue against, you'd have to just file a feature request here:

https://ideas.circleci.com

or bug folks on Discuss more

i think there are reasons we don't use a `login` shell by default....

i think you can set it with `ENV` without overriding, just append `~/.local/bin` to the existing `PATH` variable in your `ENV` decalaration

**Pull request merged**
